//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.18 at 09:47:43 PM EET 
//


package com.example.planes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Chars complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Chars">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.example.com/planes}Type"/>
 *         &lt;element name="seats" type="{http://www.example.com/planes}Seats"/>
 *         &lt;element name="armaments" type="{http://www.example.com/planes}Armaments" minOccurs="0"/>
 *         &lt;element name="radar" type="{http://www.example.com/planes}Radar"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Chars", propOrder = {
    "type",
    "seats",
    "armaments",
    "radar"
})
public class Chars {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Type type;
    @XmlSchemaType(name = "integer")
    protected int seats;
    protected Armaments armaments;
    @XmlElement(required = true)
    protected Radar radar;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the seats property.
     * 
     */
    public int getSeats() {
        return seats;
    }

    /**
     * Sets the value of the seats property.
     * 
     */
    public void setSeats(int value) {
        this.seats = value;
    }

    /**
     * Gets the value of the armaments property.
     * 
     * @return
     *     possible object is
     *     {@link Armaments }
     *     
     */
    public Armaments getArmaments() {
        return armaments;
    }

    /**
     * Sets the value of the armaments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Armaments }
     *     
     */
    public void setArmaments(Armaments value) {
        this.armaments = value;
    }

    /**
     * Gets the value of the radar property.
     * 
     * @return
     *     possible object is
     *     {@link Radar }
     *     
     */
    public Radar getRadar() {
        return radar;
    }

    /**
     * Sets the value of the radar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Radar }
     *     
     */
    public void setRadar(Radar value) {
        this.radar = value;
    }

    @Override
    public String toString() {
        String text = "\nChars: " + "\n\tType: " + type.value() + "\n\tSeats: " + seats;
        if (armaments != null) {
            text += "\n\tArmaments: " + "\n\t\tRockets: " + armaments.getRockets();
        }
        text += "\n\tRadar: " + radar.isEquipped();

        return text;
    }

}
